### ISSUE TITLE
null pointer

### ISSUE THREAD

**Issue by kalw** [javabean/iNotes-exporter#1]
Hi there,

i'm a bit confused regarding the execution of all this wonderful bunch of code.

Any help on this one ? =)

When i trigger :

```
mvn assembly:assembly -DdescriptorId=jar-with-dependencies -DskipTests
```

i got a :

```
coincoin:iNotes-exporter despresr$ java -jar target/iNotes-exporter-0.1-SNAPSHOT- ../test
iNotes-exporter-0.1-SNAPSHOT-jar-with-dependencies.jar  iNotes-exporter-0.1-SNAPSHOT-sources.jar                
coincoin:iNotes-exporter despresr$ java -cp target/iNotes-exporter-0.1-SNAPSHOT-jar-with-dependencies.jar fr.cedrik.inotes.mbox.MBoxrd ../test
755 INFO Session - Authentication successful for user "rdespres"
[Fatal Error] :1:43: Premature end of file.
898 ERROR XMLConverter - 
org.xml.sax.SAXParseException: Premature end of file.
    at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:249)
    at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:284)
    at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:124)
    at fr.cedrik.inotes.XMLConverter.convertXML(XMLConverter.java:42)
    at fr.cedrik.inotes.Session.getMessagesMetaData(Session.java:195)
    at fr.cedrik.inotes.mbox.BaseMBox.run(BaseMBox.java:71)
    at fr.cedrik.inotes.mbox.MBoxrd.main(MBoxrd.java:39)
Exception in thread "main" java.lang.NullPointerException
    at fr.cedrik.inotes.Session.getMessagesMetaData(Session.java:199)
    at fr.cedrik.inotes.mbox.BaseMBox.run(BaseMBox.java:71)
    at fr.cedrik.inotes.mbox.MBoxrd.main(MBoxrd.java:39)
```

**Comment by javabean** [comment]
This issue is due to a different webmail URL syntax than mine. A fix is forthcoming.

**Comment by javabean** [comment]
Fixed! Thanks for the bug report!
