### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by kalw** [javabean/iNotes-exporter#4]
Hello,

One of the two last commit brought some noise =)

```
$ mvn clean
$ java -cp target/iNotes-exporter-1.0.jar fr.cedrik.inotes.mbox.MBoxrd ../test.mboxrd.`date +%Y-%m-%d` 
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/io/output/FileWriterWithEncoding
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.output.FileWriterWithEncoding
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
```

**Comment by javabean** [comment]
Please use the jar-with-dependancies, or add the required dependancies on your class path!
